apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c1msxl266-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c1msxl266-python 
  name: c1msxl266-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c1msxl266-python 
